### ISSUE TITLE
TypeError: Cannot read property 'parent' of undefined

### ISSUE THREAD

**Issue by vmweaver** [haruny/adt-pulse-mqtt#12]
The Addon will run for a bit, but then fail with this:
I am running ver. 0.2.1.1 of the addon.

2018-8-2 21:48:45 Pulse.Sync: Syncing 10057-0-0
/usr/src/app/node_modules/cheerio/lib/parse.js:69
    var oldParent = node.parent || node.root,
                         ^
TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (/usr/src/app/node_modules/cheerio/lib/parse.js:69:26)
    at module.exports (/usr/src/app/node_modules/cheerio/lib/parse.js:19:11)
    at Function.exports.load (/usr/src/app/node_modules/cheerio/lib/static.js:27:14)
    at Request._callback (/usr/src/app/adt-pulse.js:216:17)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pulse-adt-mqtt@0.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pulse-adt-mqtt@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-03T02_48_47_650Z-debug.log

**Comment by haruny** [comment]
yes. when you have a shaky internet connection and the response fails, it might do this.
I'll add some error handling.

**Comment by haruny** [comment]
added error handling here in 0.2.1.2

**Comment by vmweaver** [comment]
Thank you! Very much appreciate the fine work you are doing here.

**Comment by vmweaver** [comment]
Seems I am getting another error on the new version.
It looks like "body" may be NULL in some case, would it make sense to handle that as a catchall?
I do have a solid internet connection, so I am not sure what would be causing this so regularly.  I will dig into that more.
Thanks again!


2018-8-3 06:37:12 Pulse.getDeviceStatus No other devices found
2018-8-3 06:37:12 Pulse.Sync: Syncing 10071-0-0
2018-8-3 06:37:12 Pulse: updateAll
2018-8-3 06:37:12 Pulse.getAlarmStatus: Getting Alarm Statuses
2018-8-3 06:37:17 Pulse.Sync: Syncing 10071-0-0
2018-8-3 06:37:22 Pulse.Sync: Syncing 10071-0-0
/usr/src/app/adt-pulse.js:297
				if (body.includes("You have not yet signed in")){
				         ^
TypeError: Cannot read property 'includes' of undefined
    at Request._callback (/usr/src/app/adt-pulse.js:297:14)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pulse-adt-mqtt@0.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pulse-adt-mqtt@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-03T11_37_23_104Z-debug.log

**Comment by haruny** [comment]
thanks for the feedback!
I'm not sure why it would fail to get the "body". Maybe pulse's service is up/down?
Definitely mode error handling can help.

**Comment by vmweaver** [comment]
After the last update, this is solid! Thanks.
