### ISSUE TITLE
Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by haruny** [haruny/adt-pulse-mqtt#14]
Reported by damien at community.home-assistant.io
The alarm stays stuck to “Armed Away”, but I know the alarm is disarmed.

```
2018-8-11 10:24:00 Pulse.Sync: Syncing 6383-0-0
2018-8-11 10:24:10 Pulse.Sync: Syncing undefined
2018-8-11 10:24:10 Pulse.Sync: Sync Failed
2018-8-11 10:24:15 Pulse: Login called Authenticating
2018-8-11 10:26:20 Pulse.Sync: Syncing undefined
2018-8-11 10:26:20 Pulse.Sync: Sync Failed
/usr/src/app/adt-pulse.js:88
					if (hResp.request==null){
					          ^

TypeError: Cannot read property 'request' of undefined
    at Request._callback (/usr/src/app/adt-pulse.js:88:16)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pulse-adt-mqtt@0.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pulse-adt-mqtt@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-11T14_26_26_489Z-debug.log
```

Additional logs:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pulse-adt-mqtt@0.0.1~prestart: pulse-adt-mqtt@0.0.1
6 info lifecycle pulse-adt-mqtt@0.0.1~start: pulse-adt-mqtt@0.0.1
7 verbose lifecycle pulse-adt-mqtt@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle pulse-adt-mqtt@0.0.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle pulse-adt-mqtt@0.0.1~start: CWD: /usr/src/app
10 silly lifecycle pulse-adt-mqtt@0.0.1~start: Args: [ '-c', 'node server.js' ]
11 silly lifecycle pulse-adt-mqtt@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle pulse-adt-mqtt@0.0.1~start: Failed to exec start script
13 verbose stack Error: pulse-adt-mqtt@0.0.1 start: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid pulse-adt-mqtt@0.0.1
15 verbose cwd /usr/src/app
16 verbose Linux 4.9.0-7-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error pulse-adt-mqtt@0.0.1 start: `node server.js`
22 error Exit status 1
23 error Failed at the pulse-adt-mqtt@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mbrentrowe** [comment]
Just a heads up that I had this same issue and it stopped. After restarting the add-on it is working normally.

**Comment by vmweaver** [comment]
perhaps this should be:
 " if (hResp==null){"

If the hResp is left undefined, then it will not have a .request property
(which is what is generating this error, I believe).

**Comment by haruny** [comment]
attempted a fix.
