### ISSUE TITLE
Door sensors not working

### ISSUE THREAD

**Issue by frederuco** [haruny/adt-pulse-mqtt#39]
I had this working for a while, but I think when I updated to Hass.io 112.0 the sensors (door, glass break and smoke alarm) stopped reporting to MQTT.

I have them set up as adt/zone/<PULSE NAME>/state, however when I use MQTT explorer I find no adt topic folder anywhere.

The home/alarm updates promptly when I arm or disarm, so I know that the add on is communicating with the MQTT broker properly.  Did something break so I can no longer get my door sensors?

**Comment by haruny** [comment]
I just checked. Mine working fine. do you see anything in the logs?

**Comment by frederuco** [comment]
Thanks for taking the time to check in on this.

From my logs:
7/20/2020, 6:50:19 AM Pulse: updateAll
7/20/2020, 6:50:19 AM Pulse.getAlarmStatus: Getting Alarm Statuses
7/20/2020, 6:50:24 AM Pulse.Sync: Syncing XXXXX-XXXXX-X
7/20/2020, 6:50:27 AM Pulse.getDeviceStatus: Getting Device Statuses
7/20/2020, 6:50:27 AM Pulse.getZoneStatus: Getting Zone Statuses
7/20/2020, 6:50:29 AM Pulse: Invalid Zone JSONTypeError: Cannot read property 'items' of null
    at Request._callback (/usr/src/app/adt-pulse.js:184:12)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
7/20/2020, 6:50:29 AM Pulse.getDeviceStatus No other devices found

**Comment by haruny** [comment]
are you sure you're on the latest version?
do you mind an uninstall/reinstall? don't forget to backup your config.

**Comment by frederuco** [comment]
Oh shoot, I was on 2.2.0 not 2.3.0.  Updating it fixed the issue.  Sorry to bother you.

**Comment by haruny** [comment]
no worries.
